export function throwError() {
    throw new Error('Error created')
}
